name: sintetico
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: 5.6.7
  firebase_database: ^11.0.4
  firebase_storage: ^12.4.6
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.7.0
  provider: ^6.0.5
  image_picker: ^1.1.2
  google_maps_flutter: ^2.12.2
  flutter_map: ^5.0.0
  latlong2: ^0.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true