// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqXRr7kvRS6yUUJpeAPYUkBJ0TqHrULf0',
    appId: '1:841619736296:web:6847e09db6d8ebc38b6b5d',
    messagingSenderId: '841619736296',
    projectId: 'canchita-app-7e55c',
    authDomain: 'canchita-app-7e55c.firebaseapp.com',
    storageBucket: 'canchita-app-7e55c.firebasestorage.app',
    measurementId: 'G-4M7CWTJYC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjMkI0Oay6iYK0LZZVkgrE6nV6Q6AUfSc',
    appId: '1:841619736296:android:39aac2751e3e28688b6b5d',
    messagingSenderId: '841619736296',
    projectId: 'canchita-app-7e55c',
    storageBucket: 'canchita-app-7e55c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqXRr7kvRS6yUUJpeAPYUkBJ0TqHrULf0',
    appId: '1:841619736296:web:ce0652e9d56d517b8b6b5d',
    messagingSenderId: '841619736296',
    projectId: 'canchita-app-7e55c',
    authDomain: 'canchita-app-7e55c.firebaseapp.com',
    storageBucket: 'canchita-app-7e55c.firebasestorage.app',
    measurementId: 'G-4Q36B9YP9E',
  );
}
